# Generated by Django 3.1.2 on 2020-10-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('uname', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
