import numpy as np
from tensorflow.keras.models import load_model
import wikipedia

def predict(symptoms):

    index_to_class = {
         0: '(vertigo) Paroymsal  Positional Vertigo',
         1: 'AIDS',
         2: 'Acne',
         3: 'Alcoholic hepatitis',
         4: 'Allergy',
         5: 'Arthritis',
         6: 'Bronchial Asthma',
         7: 'Cervical spondylosis',
         8: 'Chicken pox',
         9: 'Chronic cholestasis',
         10: 'Common Cold',
         11: 'Dengue',
         12: 'Diabetes ',
         13: 'Dimorphic hemmorhoids(piles)',
         14: 'Drug Reaction',
         15: 'Fungal infection',
         16: 'GERD',
         17: 'Gastroenteritis',
         18: 'Heart attack',
         19: 'Hepatitis B',
         20: 'Hepatitis C',
         21: 'Hepatitis D',
         22: 'Hepatitis E',
         23: 'Hypertension ',
         24: 'Hyperthyroidism',
         25: 'Hypoglycemia',
         26: 'Hypothyroidism',
         27: 'Impetigo',
         28: 'Jaundice',
         29: 'Malaria',
         30: 'Migraine',
         31: 'Osteoarthristis',
         32: 'Paralysis (brain hemorrhage)',
         33: 'Peptic ulcer diseae',
         34: 'Pneumonia',
         35: 'Psoriasis',
         36: 'Tuberculosis',
         37: 'Typhoid',
         38: 'Urinary tract infection',
         39: 'Varicose veins',
         40: 'hepatitis A'
    }

    symptom_to_index = {
         'itching': 0,
         'skinrash': 1,
         'nodalskineruptions': 2,
         'continuoussneezing': 3,
         'shivering': 4,
         'chills': 5,
         'jointpain': 6,
         'stomachpain': 7,
         'acidity': 8,
         'ulcersontongue': 9,
         'musclewasting': 10,
         'vomiting': 11,
         'burningmicturition': 12,
         'spotting urination': 13,
         'fatigue': 14,
         'weightgain': 15,
         'anxiety': 16,
         'coldhandsandfeets': 17,
         'moodswings': 18,
         'weightloss': 19,
         'restlessness': 20,
         'lethargy': 21,
         'patchesinthroat': 22,
         'irregularsugarlevel': 23,
         'cough': 24,
         'highfever': 25,
         'sunkeneyes': 26,
         'breathlessness': 27,
         'sweating': 28,
         'dehydration': 29,
         'indigestion': 30,
         'headache': 31,
         'yellowishskin': 32,
         'darkurine': 33,
         'nausea': 34,
         'lossofappetite': 35,
         'painbehindtheeyes': 36,
         'backpain': 37,
         'constipation': 38,
         'abdominalpain': 39,
         'diarrhoea': 40,
         'mildfever': 41,
         'yellowurine': 42,
         'yellowingofeyes': 43,
         'acuteliverfailure': 44,
         'fluidoverload': 45,
         'swellingofstomach': 46,
         'swelledlymphnodes': 47,
         'malaise': 48,
         'blurredanddistortedvision': 49,
         'phlegm': 50,
         'throatirritation': 51,
         'rednessofeyes': 52,
         'sinuspressure': 53,
         'runnynose': 54,
         'congestion': 55,
         'chestpain': 56,
         'weaknessinlimbs': 57,
         'fastheartrate': 58,
         'painduringbowelmovements': 59,
         'paininanalregion': 60,
         'bloodystool': 61,
         'irritationinanus': 62,
         'neckpain': 63,
         'dizziness': 64,
         'cramps': 65,
         'bruising': 66,
         'obesity': 67,
         'swollenlegs': 68,
         'swollenbloodvessels': 69,
         'puffyfaceandeyes': 70,
         'enlargedthyroid': 71,
         'brittlenails': 72,
         'swollenextremeties': 73,
         'excessivehunger': 74,
         'extramaritalcontacts': 75,
         'dryingandtinglinglips': 76,
         'slurredspeech': 77,
         'kneepain': 78,
         'hipjointpain': 79,
         'muscleweakness': 80,
         'stiffneck': 81,
         'swellingjoints': 82,
         'movementstiffness': 83,
         'spinningmovements': 84,
         'lossofbalance': 85,
         'unsteadiness': 86,
         'weaknessofonebodyside': 87,
         'lossofsmell': 88,
         'bladderdiscomfort': 89,
         'foulsmellof urine': 90,
         'continuousfeelofurine': 91,
         'passageofgases': 92,
         'internalitching': 93,
         'toxiclook(typhos)': 94,
         'depression': 95,
         'irritability': 96,
         'musclepain': 97,
         'alteredsensorium': 98,
         'redspotsoverbody': 99,
         'bellypain': 100,
         'abnormalmenstruation': 101,
         'dischromic patches': 102,
         'wateringfromeyes': 103,
         'increasedappetite': 104,
         'polyuria': 105,
         'familyhistory': 106,
         'mucoidsputum': 107,
         'rustysputum': 108,
         'lackofconcentration': 109,
         'visualdisturbances': 110,
         'receivingbloodtransfusion': 111,
         'receivingunsterileinjections': 112,
         'coma': 113,
         'stomachbleeding': 114,
         'distentionofabdomen': 115,
         'historyofalcoholconsumption': 116,
         'fluidoverload.1': 117,
         'bloodinsputum': 118,
         'prominentveinsoncalf': 119,
         'palpitations': 120,
         'painfulwalking': 121,
         'pusfilledpimples': 122,
         'blackheads': 123,
         'scurring': 124,
         'skinpeeling': 125,
         'silverlikedusting': 126,
         'smalldentsinnails': 127,
         'inflammatorynails': 128,
         'blister': 129,
         'redsorearoundnose': 130,
         'yellowcrustooze': 131
    }

    model = load_model(r'model/load_model/model.hdf5', compile=False)

    symptoms = symptoms.replace(' ', '')
    symptoms = symptoms.lower()
    symptoms = symptoms.split(',')

    input_data = np.zeros((1,132))

    for i in symptoms:
        if symptom_to_index.get(i) != None:
            input_data[0, symptom_to_index[i]] = 1

    pred = model.predict(input_data)
    pred = index_to_class[np.argmax(pred)]
    summary = wikipedia.summary(pred, sentences=3)
    return (pred, summary)